version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"